summaryLength = 120
hasCJKLanguage = true
relativeurls = true


baseURL = "https://ohmykevin.github.io/"
languageCode = "en-us"
title = "Kevin's Blog"
theme="tophat"
paginate = 5

[menu]
  [[menu.main]]
    identifier = "home"
    name = "ğŸ Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "archives"
    name = "ğŸ“‡Archives"
    url = "/archives"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "ğŸ™‚About"
    url = "/about"
    weight =30




[params]
    
  subtitle = "Life & Code"
  description = "life,code,journal"
  author = "Kevin"

  main = "posts"
  featured = true
  
  # You can customize the visibility of some elements like date, reading time, words counter and tags inside article by setting true or false
  show_date_on_article = true
  show_reading_time_on_article = false
  show_words_count_on_article = false
  show_tags_on_article = true


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true